server.port: 7001
server:
  error:
    include-message: always


spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: product-db

  cloud:
    function:
      definition: messageProcessor
    stream:
      bindings:
        messageProcessor-in-0:
          destination: products
          group: productsGroup
          content-type: application/json
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-multiplier: 2.0
            back-off-max-interval: 1000

      rabbit:
        bindings:
          messageProcessor-in-0.consumer:
            auto-bind-dlq: true
            republish-to-dlq: true

      kafka:
        bindings:
          messageProcessor-in-0.consumer:
            enable-dlq: true

logging:
  level:
    root: INFO
    com.kimsang: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

server.port: 8080
