springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v1/api-docs
  packagesToScan: com.kimsang.microservices.composite.product
  pathsToMatch: /**
  cache.disabled: true

  swagger-ui:
    oauth2-redirect-url: https://localhost:8443/swagger-ui/oauth2-redirect.html
    oauth:
      clientId: writer
      clientSecret: secret
      useBasicAuthenticationWithAccessCodeGrant: true

  oAuthFlow:
    authorizationUrl: https://localhost:8443/oauth2/authorize
    tokenUrl: https://localhost:8443/oauth2/token

api:

  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfService: MY TERMS OF SERVICE
    license: MY LICENSE
    licenseUrl: MY LICENSE URL

    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: NAME OF CONTACT
      url: URL TO CONTACT
      email: contact@mail.com

server:
  port: 7000
  error:
    include-message: always
  forward-headers-strategy: framework


spring:
  test:
    context:
      failure:
        threshold: 10

  cloud:
    stream:
      bindings:
        products-out-0:
          destination: products
          producer:
            required-groups: auditGroup
        recommendations-out-0:
          destination: recommendations
          producer:
            required-groups: auditGroup
        reviews-out-0:
          destination: reviews
          producer:
            required-groups: auditGroup
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.auth-server}:9999

resilience4j.timelimiter:
  instances:
    product:
      timeoutDuration: 2s
resilience4j.retry:
  instances:
    product:
      maxAttempts: 3
      waitDuration: 1000
      retryExceptions:
        - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError

management.health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  instances:
    product:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - com.kimsang.api.exceptions.InvalidInputException
        - com.kimsang.api.exceptions.NotFoundException



logging:
  level:
    root: INFO
    com.kimsang: INFO
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: INFO
    # To see tracing headers, uncomment the following two lines and restart the product-composite service
    # spring.codec.log-request-details: true
    # logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080


---
spring.config.activate.on-profile: streaming_partitioned

spring:
  cloud:
    stream:
      bindings:
        products-out-0.producer:
          partition-key-expression: headers['partitionKey']
          partition-count: 2

        recommendations-out-0.producer:
          partition-key-expression: headers['partitionKey']
          partition-count: 2

        reviews-out-0.producer:
          partition-key-expression: headers['partitionKey']
          partition-count: 2
