server:
  port: 7003
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviewdb
    username: root
    password: '{cipher}f80e46219c36d3fedcdbeb0ad7c525c1fe10f7e317df459ff5a8bc74a0715a81'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      # Strongly recommend to set this property to "none" in a production environment!
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    function:
      definition: messageProcessor
    stream:
      bindings:
        messageProcessor-in-0:
          destination: reviews
          group: reviewsGroup
          content-type: application/json
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-multiplier: 2.0
            back-off-max-interval: 1000

      rabbit:
        bindings:
          messageProcessor-in-0.consumer:
            auto-bind-dlq: true
            republish-to-dlq: true

      kafka:
        bindings:
          messageProcessor-in-0.consumer:
            enable-dlq: true

logging:
  level:
    root: INFO
    com.kimsang: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql/review-db
    username: root
    password: rootpwd

server:
  port: 8080