server:
  port: 7002
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      bindings:
        messageProcessor-in-0:
          destination: recommendations
          group: recommendationsGroup
          content-type: application/json
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-multiplier: 2.0
            back-off-max-interval: 1000

      rabbit:
        bindings:
          messageProcessor-in-0.consumer:
            auto-bind-dlq: true
            republish-to-dlq: true

      kafka:
        bindings:
          messageProcessor-in-0.consumer:
            enable-dlq: true

        binder:
          brokers: 127.0.0.1:9092

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


logging:
  level:
    root: INFO
    com.kimsang: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

server:
  port: 8080

