server:
  port: 7000
  error:
    include-message: always

app:
  product-service:
    host: localhost
    port: 7001

logging:
  level:
    root: INFO
    com.kimsang: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080
app:
  product-service:
    host: product
    port: 8080
