server:
  port: 7000
  error:
    include-message: always

spring.application.name: product-composite

logging:
  level:
    root: INFO
    com.kimsang: DEBUG

spring:
  cloud:
    stream:
      default-binder: rabbit

      bindings:
        products-out-0:
          destination: products
          producer:
            required-groups: auditGroup
        recommendations-out-0:
          destination: recommendations
          producer:
            required-groups: auditGroup
        reviews-out-0:
          destination: reviews
          producer:
            required-groups: auditGroup

      kafka:
        binder:
          brokers: 127.0.0.1:9092

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
debug: true
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

---
spring.config.activate.on-profile: streaming_partitioned

spring:
  cloud:
    stream:
      bindings:
        products-out-0.producer:
          partition-key-expression: headers['partitionKey']
          partition-count: 2

        recommendations-out-0.producer:
          partition-key-expression: headers['partitionKey']
          partition-count: 2

        reviews-out-0.producer:
          partition-key-expression: headers['partitionKey']
          partition-count: 2


---
spring.config.activate.on-profile: kafka

management.health.rabbit.enabled: false
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          replication-factor: 1

  kafka:
    bootstrap-servers: kafka:9092


