server:
  port: 7003
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviewdb
    username: root
    password: kimsangkafka
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      bindings:
        messageProcessor-in-0:
          destination: recommendations
          group: recommendationsGroup
          content-type: application/json
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-multiplier: 2.0
            back-off-max-interval: 1000

      rabbit:
        bindings:
          messageProcessor-in-0.consumer:
            auto-bind-dlq: true
            republish-to-dlq: true

      kafka:
        bindings:
          messageProcessor-in-0.consumer:
            enable-dlq: true

        binder:
          brokers: 127.0.0.1:9092

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


logging:
  level:
    root: INFO
    com.kimsang: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql/review-db
    username: root
    password: rootpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

server:
  port: 8080